/*
 * The Good Stuff DS runtime: draws whatever `gs_scene` (source/scene_data.c, generated by the
 * compiler) describes. There is deliberately no scene logic here — no node kinds, no transform
 * composition, no hierarchy. If the runtime needs to know something, the data says it.
 *
 * Requirements: requirements/compiler/TASK.ds-runtime-c-template.md
 */
#include <nds.h>

#include "scene.h"

/* Material colors shared by every mesh until the scene model has materials. */
#define AMBIENT_COLOR RGB15(8, 8, 8)

/* The 3D backdrop. Not black, so screenshots can find the screen (tests read this value). */
#define CLEAR_R 3
#define CLEAR_G 5
#define CLEAR_B 10

static void draw_mesh(const GsMesh *mesh) {
	const GsPrimitive *primitive = &gs_scene.primitives[mesh->primitive];
	const int16_t *p = primitive->positions;
	const uint32_t *n = primitive->normals;
	int vertexCount = primitive->triangleCount * 3;

	glPushMatrix();
	glMultMatrix4x4((const m4x4 *)&mesh->world);

	glMaterialf(GL_AMBIENT, AMBIENT_COLOR);
	glMaterialf(GL_DIFFUSE, mesh->diffuse);
	glMaterialf(GL_SPECULAR, RGB15(0, 0, 0));
	glMaterialf(GL_EMISSION, RGB15(0, 0, 0));

	glBegin(GL_TRIANGLES);
	for (int i = 0; i < vertexCount; i++) {
		glNormal(n[i]);
		glVertex3v16(p[i * 3], p[i * 3 + 1], p[i * 3 + 2]);
	}
	glEnd();

	glPopMatrix(1);
}

int main(void) {
	/* The DS can only drive 3D on one screen; the scene says which. */
	if (gs_scene.screen == 0) {
		lcdMainOnTop();
	} else {
		lcdMainOnBottom();
	}

	videoSetMode(MODE_0_3D);
	videoSetModeSub(MODE_0_2D); /* the other screen stays a plain backdrop */
	setBackdropColorSub(RGB15(0, 0, 0));

	glInit();
	glClearColor(CLEAR_R, CLEAR_G, CLEAR_B, 31); /* opaque: a visible backdrop, so a picture of the screen shows where its edges are */
	glClearPolyID(63);
	glClearDepth(0x7FFF);
	glViewport(0, 0, 255, 191);

	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	gluPerspective(gs_scene.fovDegrees, 256.0f / 192.0f, gs_scene.nearPlane, gs_scene.farPlane);
	glMatrixMode(GL_MODELVIEW);

	/* 60 fps waits one vertical blank per frame, 30 fps waits two. */
	const int framesPerPresent = gs_scene.fps == 30 ? 2 : 1;

	uint32_t polyFormat = POLY_ALPHA(31) | POLY_CULL_NONE;
	for (int i = 0; i < gs_scene.lightCount && i < 4; i++) {
		polyFormat |= POLY_FORMAT_LIGHT0 << i;
	}

	while (pmMainLoop()) {
		/* The camera. Lights are set with only the view loaded, because the geometry engine
		   transforms a light's direction by the current matrix when the light is set. */
		glLoadMatrix4x4((const m4x4 *)&gs_scene.view);
		for (int i = 0; i < gs_scene.lightCount && i < 4; i++) {
			const GsLight *light = &gs_scene.lights[i];
			glLight(i, light->color, light->direction[0], light->direction[1], light->direction[2]);
		}

		glPolyFmt(polyFormat);
		for (int i = 0; i < gs_scene.meshCount; i++) {
			draw_mesh(&gs_scene.meshes[i]);
		}

		glFlush(0);
		for (int i = 0; i < framesPerPresent; i++) {
			swiWaitForVBlank();
		}
	}

	return 0;
}
