/*
 * The Good Stuff DS runtime: draws whatever `gs_scene` (source/scene_data.c, generated by the compiler) describes and runs the scripts
 * in source/script_code.c (also generated). There is deliberately no game logic here — no node kinds beyond what drawing needs. If the
 * runtime needs to know something, the data says it.
 *
 * Requirements: requirements/compiler/TASK.ds-runtime-c-template.md, TASK.runtime-node-table-and-script-services.md
 */
#include <nds.h>
#include <stdlib.h>

#include "gs_api.h"
#include "gs_runtime.h"
#include "scene.h"

/* Material colors shared by every mesh until the scene model has materials. */
#define AMBIENT_COLOR RGB15(8, 8, 8)

/* The 3D backdrop. Not black, so screenshots can find the screen (tests read this value). */
#define CLEAR_R 3
#define CLEAR_G 5
#define CLEAR_B 10

/* ---- Drawing ---------------------------------------------------------------------------------------------------------------------- */

/* The texture names glGenTextures gave each of gs_scene.textures, in order. */
static int *textureNames;

/* Uploads every texture to texture memory once, at startup. */
static void load_textures(void) {
	if (gs_scene.textureCount == 0) return;
	textureNames = malloc(sizeof(int) * gs_scene.textureCount);
	glGenTextures(gs_scene.textureCount, textureNames);
	for (int i = 0; i < gs_scene.textureCount; i++) {
		const GsTexture *texture = &gs_scene.textures[i];
		glBindTexture(0, textureNames[i]);
		/* sizeS/sizeT are the DS's size classes (TEXTURE_SIZE_8 is 0 ... TEXTURE_SIZE_1024 is 7). Wrapping is on, so a coordinate past the edge tiles the picture. */
		glTexImage2D(0, 0, GL_RGBA, texture->sizeS, texture->sizeT, 0,
			TEXGEN_TEXCOORD | GL_TEXTURE_WRAP_S | GL_TEXTURE_WRAP_T, texture->texels);
	}
}

static void draw_mesh(const GsMesh *mesh, int index, int lit) {
	const GsPrimitive *primitive = &gs_scene.primitives[gs_mesh_primitive(index)];
	const int16_t *p = primitive->positions;
	const uint32_t *n = primitive->normals;
	const int16_t *uv = mesh->texture ? primitive->texcoords : 0;
	int vertexCount = primitive->triangleCount * 3;

	/* Binding texture 0 turns texturing off for the polygons that follow. */
	glBindTexture(0, uv ? textureNames[mesh->texture - 1] : 0);

	glPushMatrix();
	/* Rotation and translation go to the position matrix AND the vector (normal) matrix. Scale is applied to the
	   position matrix alone: the geometry engine transforms a normal by the same matrix as a position and never
	   renormalizes it, so scale left in the vector matrix would lengthen or shorten every normal and wreck the
	   lighting (a mesh scaled 3x got no light at all). */
	glMultMatrix4x4((const m4x4 *)&gs_world_matrix[mesh->node]);
	glMatrixMode(GL_POSITION);
	glScalef32(gs_world_scale[mesh->node][0], gs_world_scale[mesh->node][1], gs_world_scale[mesh->node][2]);
	glMatrixMode(GL_MODELVIEW);

	glMaterialf(GL_AMBIENT, AMBIENT_COLOR);
	glMaterialf(GL_DIFFUSE, mesh->diffuse);
	glMaterialf(GL_SPECULAR, RGB15(0, 0, 0));
	/* Every glNormal recomputes the vertex color as emission + the enabled lights' contributions, so with no lights the color is just the
	   emission, and that is what an unlit mesh shows: its own color, full brightness. (With emission left at black, a scene with no
	   light drew pure black.) */
	glMaterialf(GL_EMISSION, lit ? RGB15(0, 0, 0) : mesh->diffuse);

	glBegin(GL_TRIANGLES);
	for (int i = 0; i < vertexCount; i++) {
		if (uv) glTexCoord2t16(uv[i * 2], uv[i * 2 + 1]);
		glNormal(n[i]);
		glVertex3v16(p[i * 3], p[i * 3 + 1], p[i * 3 + 2]);
	}
	glEnd();

	glPopMatrix(1);
}

/* The camera's view, as the scene starts or as a script has moved it. */
static void load_view(void) {
	GsMatrix view;
	gs_compute_view(&view);
	glLoadMatrix4x4((const m4x4 *)&view);
}

/* The scripts of the scene being shown. */
static const GsScriptInstance *scriptInstances;
static uint16_t scriptCount;

/*
 * Shows scene `index` of the project (the starting scene is 0): the screen the 3D is on, the VRAM banks, the camera's lens, the textures, every table the runtime keeps for a scene, the
 * scripts' starting values and their `_ready`. `first` is the start of the game; otherwise the scene being shown is put away first (its sounds stopped, its memory given back, its
 * textures and sprites cleared).
 */
static void enter_scene(int index, int first) {
	if (!first) {
		gs_leave_scene();
		glResetTextures();
	}
	gs_scene_current = gs_scene_table[index];

	/* The DS can only drive 3D on one screen; the scene says which. */
	if (gs_scene.screen == 0) {
		lcdMainOnTop();
	} else {
		lcdMainOnBottom();
	}

	videoSetMode(MODE_0_3D);
	videoSetModeSub(MODE_0_2D); /* the other screen stays a plain backdrop */
	setBackdropColorSub(RGB15(0, 0, 0));

	/* All four VRAM banks are texture memory: 512 KB, which is the budget the compiler checks against. */
	vramSetBankA(VRAM_A_TEXTURE);
	vramSetBankB(VRAM_B_TEXTURE);
	vramSetBankC(VRAM_C_TEXTURE);
	/* ... unless the 2D screen has sprites: the sub engine's sprite tiles need a bank of their own (D), and textures keep A to C (384 KB, which is the budget the
	   compiler checks against in that case). */
	if (gs_scene.sprites2D.spriteCount > 0) {
		vramSetBankD(VRAM_D_SUB_SPRITE);
	} else {
		vramSetBankD(VRAM_D_TEXTURE);
	}
	/* Text on the 2D screen is a background of the sub engine, in bank H (32 KB, otherwise unused). */
	if (gs_scene.sprites2D.labelCount > 0) vramSetBankH(VRAM_H_SUB_BG);

	if (first) {
		glInit();
		glEnable(GL_TEXTURE_2D);
		glClearColor(CLEAR_R, CLEAR_G, CLEAR_B, 31); /* opaque: a visible backdrop, so a picture of the screen shows where its edges are */
		glClearPolyID(63);
		glClearDepth(0x7FFF);
		glViewport(0, 0, 255, 191);
	}
	free(textureNames);
	textureNames = 0;
	load_textures();

	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	gluPerspective(gs_scene.fovDegrees, 256.0f / 192.0f, gs_scene.nearPlane, gs_scene.farPlane);
	glMatrixMode(GL_MODELVIEW);

	gs_init_nodes();
	gs_init_mesh_anim();
	gs_init_touch();
	gs_init_sprites();
	gs_init_labels();
	gs_init_audio();
	gs_start_audio();
	gs_init_animation();
	gs_update_nodes();
	const GsSceneScripts *scripts = &gs_scene_scripts[index];
	scripts->reset();
	scriptInstances = scripts->instances;
	scriptCount = *scripts->count;
	for (int i = 0; i < scriptCount; i++) {
		const GsScriptInstance *script = &scriptInstances[i];
		if (script->ready) script->ready(script->inst);
	}
}

int main(void) {
	enter_scene(0, 1);

	/* 60 fps waits one vertical blank per frame, 30 fps waits two. */
	const int framesPerPresent = gs_scene.fps == 30 ? 2 : 1;
	/* Seconds per frame, as a 20.12 number. */
	const int32_t delta = gs_scene.fps == 30 ? 137 : 68;

	while (pmMainLoop()) {
		gs_read_input();
		gs_update_touch(); /* before the scripts, which ask the touch areas */
		for (int i = 0; i < scriptCount; i++) {
			const GsScriptInstance *script = &scriptInstances[i];
			if (script->process) script->process(script->inst, delta);
		}
		gs_update_mesh_anim();
		gs_update_animation(delta); /* after the scripts: an animation wins over a script that writes the same property */
		gs_update_nodes();

		/* The camera. Lights are set with only the view loaded, because the geometry engine transforms a light's direction by the
		   current matrix when the light is set. */
		load_view();
		int active = 0;
		for (int i = 0; i < gs_scene.lightCount && active < 4; i++) {
			const GsLight *light = &gs_scene.lights[i];
			if (!gs_world_visible[light->node]) continue;
			int32_t x = light->direction[0], y = light->direction[1], z = light->direction[2];
			if (gs_scene.nodes[light->node].dynamic) {
				/* A light shines along its node's -Z axis: the third column of the rotation, negated, from 20.12 to the v10 fraction. */
				const int32_t *w = gs_world_matrix[light->node].m;
				x = gs_clamp(-w[8] >> 3, -512, 511);
				y = gs_clamp(-w[9] >> 3, -512, 511);
				z = gs_clamp(-w[10] >> 3, -512, 511);
			}
			glLight(active, light->color, x, y, z);
			active++;
		}

		uint32_t polyFormat = POLY_ALPHA(31) | POLY_CULL_NONE;
		for (int i = 0; i < active; i++) polyFormat |= POLY_FORMAT_LIGHT0 << i;
		glPolyFmt(polyFormat);
		for (int i = 0; i < gs_scene.meshCount; i++) {
			const GsMesh *mesh = &gs_scene.meshes[i];
			if (gs_world_visible[mesh->node]) draw_mesh(mesh, i, active > 0);
		}

		glFlush(0);
		for (int i = 0; i < framesPerPresent; i++) {
			swiWaitForVBlank();
			if (i == 0) {
				gs_update_sprites(); /* right after the vertical blank, where the sprite table can be copied */
				gs_update_labels();
			}
		}

		/* A script asked for another scene: it is shown from the next frame on. */
		if (gs_pending_scene >= 0) {
			const int next = gs_pending_scene;
			gs_pending_scene = -1;
			if (next < gs_scene_table_count) enter_scene(next, 0);
		}
	}

	return 0;
}
