/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */
#include "scene.h"

extern const GsScene gs_scene_data_0;

const GsScene *const gs_scene_table[] = {
  &gs_scene_data_0
};
const uint16_t gs_scene_table_count = 1;
const GsScene *gs_scene_current = &gs_scene_data_0;
