/* GENERATED by @goodstuff/compiler from the project's scripts. Do not edit: the next build overwrites this file. */
#include <string.h>
#include "gs_api.h"

#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"

const GsScriptInstance gs_script_instances[] = {
	{ 0, 0, 0, 0 }
};
const uint16_t gs_script_instance_count = 0;

void gs_scripts_reset(void) {
}

/* The project's global variables: kept when the scene changes, and what the save file holds. */
#include "gs_api.h"
int32_t gs_global[1] = { 0 };
const int32_t gs_global_initial[1] = { 0 };
const uint16_t gs_global_count = 0;
const uint32_t gs_global_signature = 2166136261u;

/* The scripts of every scene. */
#include "gs_api.h"
extern const GsScriptInstance gs_script_instances[];
extern const uint16_t gs_script_instance_count;
void gs_scripts_reset(void);
const GsSceneScripts gs_scene_scripts[] = {
  { gs_script_instances, &gs_script_instance_count, gs_scripts_reset }
};
