/* GENERATED by @goodstuff/compiler from the project's scripts. Do not edit: the next build overwrites this file. */
#include "gs_api.h"

#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"

const GsScriptInstance gs_script_instances[] = {
	{ 0, 0, 0, 0 }
};
const uint16_t gs_script_instance_count = 0;
