import type { DsScene3D } from "./ds-scene";

/**
 * Serializes a translated scene as the `scene_data.c` the C runtime is built against. The output is
 * constant data only — arrays and initializers, no executable statements — and is a pure function of
 * the scene, so the same scene always produces byte-identical text.
 *
 * The struct layouts it fills in are declared by the runtime's `scene.h`
 * (packages/compiler/runtime/include/scene.h); keep the two in step.
 */

const PER_LINE = 12;

function numbers(values: readonly number[]): string {
  if (values.length === 0) return "0"; // C doesn't allow an empty array; the count says how many are real
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += PER_LINE) lines.push("  " + values.slice(i, i + PER_LINE).join(", "));
  return lines.join(",\n");
}

function matrix(m: readonly number[]): string {
  return `{ { ${m.join(", ")} } }`;
}

/** A float literal the C compiler reads back exactly. */
function float(value: number): string {
  const text = Number.isInteger(value) ? `${value}.0` : String(value);
  return `${text}f`;
}

export function writeSceneDataC(scene: DsScene3D): string {
  const out: string[] = [];
  out.push("/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */");
  out.push('#include "scene.h"');
  out.push("");

  scene.primitives.forEach((p, i) => {
    out.push(`/* ${p.primitive}: ${p.triangleCount} triangles */`);
    out.push(`static const int16_t primitive_${i}_positions[] = {\n${numbers(p.positions)}\n};`);
    out.push(`static const uint32_t primitive_${i}_normals[] = {\n${numbers(p.normals.map((n) => n))}\n};`);
    out.push("");
  });

  out.push("static const GsPrimitive primitives[] = {");
  if (scene.primitives.length === 0) out.push("  { 0, 0, 0 }");
  scene.primitives.forEach((p, i) => {
    out.push(`  { ${p.triangleCount}, primitive_${i}_positions, primitive_${i}_normals }${i < scene.primitives.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsMesh meshes[] = {");
  if (scene.meshes.length === 0) out.push("  { 0, 0, { { 0 } } }");
  scene.meshes.forEach((m, i) => {
    out.push(`  { ${m.primitive}, ${m.diffuse}, ${matrix(m.world)} }${i < scene.meshes.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsLight lights[] = {");
  if (scene.lights.length === 0) out.push("  { 0, { 0, 0, 0 } }");
  scene.lights.forEach((l, i) => {
    out.push(`  { ${l.color}, { ${l.direction.join(", ")} } }${i < scene.lights.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("const GsScene gs_scene = {");
  out.push(`  ${scene.screen === "top" ? 0 : 1}, /* screen: 0 top, 1 bottom */`);
  out.push(`  ${scene.fps}, /* fps */`);
  out.push(`  ${float(scene.camera.fovDegrees)}, ${float(scene.camera.nearPlane)}, ${float(scene.camera.farPlane)}, /* fov, near, far */`);
  out.push(`  ${matrix(scene.camera.view)}, /* view */`);
  out.push(`  ${scene.primitives.length}, ${scene.meshes.length}, ${scene.lights.length}, /* primitive, mesh, light counts */`);
  out.push("  primitives, meshes, lights");
  out.push("};");
  out.push("");
  return out.join("\n");
}
