import type { DsScene3D } from "./ds-scene";

/**
 * Serializes a translated scene as the `scene_data.c` the C runtime is built against. The output is
 * constant data only — arrays and initializers, no executable statements — and is a pure function of
 * the scene, so the same scene always produces byte-identical text.
 *
 * The struct layouts it fills in are declared by the runtime's `scene.h`
 * (packages/compiler/runtime/include/scene.h); keep the two in step.
 */

const PER_LINE = 12;

/** `GS_SHAPE_*` in the runtime's gs_collision.h. */
const SHAPE_CODES = { box: 0, sphere: 1, capsule: 2, cylinder: 3 } as const;

/** `GS_ANIM_*` in the runtime's scene.h. */
const ANIM_PROPERTY_CODES = { position: 0, rotation: 1, scale: 2, visible: 3, volume: 4, pitch: 5 } as const;

function numbers(values: readonly number[]): string {
  if (values.length === 0) return "0"; // C doesn't allow an empty array; the count says how many are real
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += PER_LINE) lines.push("  " + values.slice(i, i + PER_LINE).join(", "));
  return lines.join(",\n");
}

/**
 * Text that is safe inside a C comment on one line: printable ASCII only, and neither comment
 * delimiter can appear (a model's name comes from a file name, which can contain anything).
 */
function commentSafe(text: string): string {
  return text
    .replace(/[^ -~]/g, "?")
    .replace(/\*\//g, "* /")
    .replace(/\/\*/g, "/ *")
    .slice(0, 60);
}

/** Texels are easier to read (and to compare with the picture) in hex. */
function hexNumbers(values: readonly number[]): string {
  if (values.length === 0) return "0";
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += PER_LINE) {
    lines.push("  " + values.slice(i, i + PER_LINE).map((v) => "0x" + v.toString(16).padStart(4, "0")).join(", "));
  }
  return lines.join(",\n");
}

function matrix(m: readonly number[]): string {
  return `{ { ${m.join(", ")} } }`;
}

/** A float literal the C compiler reads back exactly. */
function float(value: number): string {
  const text = Number.isInteger(value) ? `${value}.0` : String(value);
  return `${text}f`;
}

/** The generated `script_code.c` (the scripts' functions and the table of script instances); it is built by `generateScriptCode` during translation. */
export function writeScriptCodeC(scene: DsScene3D): string {
  return scene.scriptCode;
}

export function writeSceneDataC(scene: DsScene3D): string {
  const out: string[] = [];
  out.push("/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */");
  out.push('#include "scene.h"');
  out.push("");

  scene.primitives.forEach((p, i) => {
    out.push(`/* ${commentSafe(p.label)}: ${p.triangleCount} triangles */`);
    out.push(`static const int16_t primitive_${i}_positions[] = {\n${numbers(p.positions)}\n};`);
    out.push(`static const uint32_t primitive_${i}_normals[] = {\n${numbers(p.normals.map((n) => n))}\n};`);
    if (p.texcoords) out.push(`static const int16_t primitive_${i}_texcoords[] = {\n${numbers(p.texcoords)}\n};`);
    out.push("");
  });

  scene.textures.forEach((t, i) => {
    out.push(`/* texture ${commentSafe(t.label)}: ${t.width} x ${t.height}, ${t.width * t.height * 2} bytes */`);
    out.push(`static const uint16_t texture_${i}_texels[] = {\n${hexNumbers(t.texels)}\n};`);
    out.push("");
  });
  out.push("static const GsTexture textures[] = {");
  if (scene.textures.length === 0) out.push("  { 0, 0, 0, 0, 0 }");
  scene.textures.forEach((t, i) => {
    out.push(`  { ${t.width}, ${t.height}, ${t.sizeS}, ${t.sizeT}, texture_${i}_texels }${i < scene.textures.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  // Samples are 4-byte aligned: the sound hardware reads whole words from main RAM.
  scene.sounds.forEach((s, i) => {
    out.push(`/* sound ${commentSafe(s.label)}: ${s.samples.length} samples at ${s.sampleRate} Hz, ${s.samples.length * 2} bytes */`);
    out.push(`static const int16_t sound_${i}_samples[] __attribute__((aligned(4))) = {\n${numbers(s.samples)}\n};`);
    out.push("");
  });
  out.push("static const GsSound sounds[] = {");
  if (scene.sounds.length === 0) out.push("  { 0, 0, 0 }");
  scene.sounds.forEach((s, i) => {
    out.push(`  { ${s.samples.length}, ${s.sampleRate}, sound_${i}_samples }${i < scene.sounds.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAudioPlayer audioPlayers[] = {");
  if (scene.audioPlayers.length === 0) out.push("  { 0, 0, 0, 0, 0 }");
  scene.audioPlayers.forEach((p, i) => {
    out.push(`  { ${p.sound}, ${p.frequency}, ${p.volume}, ${p.loop ? 1 : 0}, ${p.autoplay ? 1 : 0} }${i < scene.audioPlayers.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsCollider colliders[] = {");
  if (scene.colliders.length === 0) out.push("  { 0, 0, { 0, 0, 0 } }");
  scene.colliders.forEach((c, i) => {
    out.push(`  { ${SHAPE_CODES[c.shape]}, ${c.solid ? 1 : 0}, { ${c.params.join(", ")} } }${i < scene.colliders.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsAnimKey animKeys[] = {");
  if (scene.animationKeys.length === 0) out.push("  { 0, { 0, 0, 0 } }");
  scene.animationKeys.forEach((k, i) => {
    out.push(`  { ${k.time}, { ${k.value.join(", ")} } }${i < scene.animationKeys.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimTrack animTracks[] = {");
  if (scene.animationTracks.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.animationTracks.forEach((t, i) => {
    out.push(`  { ${ANIM_PROPERTY_CODES[t.property]}, ${t.node}, ${t.keyStart}, ${t.keyCount} }${i < scene.animationTracks.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimation animations[] = {");
  if (scene.animations.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.animations.forEach((a, i) => {
    out.push(`  /* ${commentSafe(a.name)} */`);
    out.push(`  { ${a.length}, ${a.loop ? 1 : 0}, ${a.trackStart}, ${a.trackCount} }${i < scene.animations.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimationPlayer animationPlayers[] = {");
  if (scene.animationPlayers.length === 0) out.push("  { 0, 0, -1, 0 }");
  scene.animationPlayers.forEach((p, i) => {
    out.push(`  { ${p.animationStart}, ${p.animationCount}, ${p.autoplay}, ${p.speed} }${i < scene.animationPlayers.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsPrimitive primitives[] = {");
  if (scene.primitives.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.primitives.forEach((p, i) => {
    const texcoords = p.texcoords ? `primitive_${i}_texcoords` : "0";
    out.push(`  { ${p.triangleCount}, primitive_${i}_positions, primitive_${i}_normals, ${texcoords} }${i < scene.primitives.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  // Every kept node, parents first. Meshes, the camera and lights say which one they are; scripts read and write the local values.
  out.push("static const GsNode nodes[] = {");
  scene.nodes.forEach((n, i) => {
    out.push(`  /* ${commentSafe(n.name)} */`);
    out.push(
      `  { ${n.parent}, ${n.dynamic ? 1 : 0}, ${n.visible ? 1 : 0}, ${n.audio}, ${n.collider}, ${n.animPlayer}, { ${n.position.join(", ")} }, { ${n.rotation.join(", ")} }, { ${n.scale.join(", ")} }, ` +
        `{ ${n.worldScale.join(", ")} }, ${matrix(n.world)} }${i < scene.nodes.length - 1 ? "," : ""}`
    );
  });
  out.push("};");
  out.push("");

  out.push("static const GsMesh meshes[] = {");
  if (scene.meshes.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.meshes.forEach((m, i) => {
    out.push(`  { ${m.primitive}, ${m.diffuse}, ${m.texture}, ${m.node} }${i < scene.meshes.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsLight lights[] = {");
  if (scene.lights.length === 0) out.push("  { 0, { 0, 0, 0 }, 0 }");
  scene.lights.forEach((l, i) => {
    out.push(`  { ${l.color}, { ${l.direction.join(", ")} }, ${l.node} }${i < scene.lights.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("const GsScene gs_scene = {");
  out.push(`  ${scene.screen === "top" ? 0 : 1}, /* screen: 0 top, 1 bottom */`);
  out.push(`  ${scene.fps}, /* fps */`);
  out.push(`  ${float(scene.camera.fovDegrees)}, ${float(scene.camera.nearPlane)}, ${float(scene.camera.farPlane)}, /* fov, near, far */`);
  out.push(`  ${matrix(scene.camera.view)}, /* view */`);
  out.push(`  ${scene.camera.node}, ${scene.nodes.length}, /* camera node, node count */`);
  out.push(`  ${scene.primitives.length}, ${scene.meshes.length}, ${scene.lights.length}, ${scene.textures.length}, /* primitive, mesh, light, texture counts */`);
  out.push(`  ${scene.sounds.length}, ${scene.audioPlayers.length}, ${scene.colliders.length}, /* sound, audio player, collider counts */`);
  out.push(`  ${scene.animationPlayers.length}, ${scene.animations.length}, ${scene.animationTracks.length}, ${scene.animationKeys.length}, /* animation player, animation, track, key counts */`);
  out.push("  nodes, primitives, meshes, lights, textures, sounds, audioPlayers, colliders, animationPlayers, animations, animTracks, animKeys");
  out.push("};");
  out.push("");
  return out.join("\n");
}
