import type { DsScene2D, DsScene3D, DsScreen2D } from "./ds-scene";

/**
 * Serializes a translated scene as the `scene_data.c` the C runtime is built against. The output is
 * constant data only — arrays and initializers, no executable statements — and is a pure function of
 * the scene, so the same scene always produces byte-identical text.
 *
 * The struct layouts it fills in are declared by the runtime's `scene.h`
 * (packages/compiler/runtime/include/scene.h); keep the two in step.
 */

const PER_LINE = 12;

/** `GS_SHAPE_*` in the runtime's gs_collision.h. */
const SHAPE_CODES = { box: 0, sphere: 1, capsule: 2, cylinder: 3, convexHull: 4 } as const;

/** `GS_ANIM_*` in the runtime's scene.h. */
/** `GS_TOUCH_*` in the runtime's scene.h. */
const TOUCH_SHAPE_CODES = { rect: 0, box: 1, sphere: 2 } as const;

const ANIM_PROPERTY_CODES = { position: 0, rotation: 1, scale: 2, visible: 3, volume: 4, pitch: 5 } as const;

/** `GS_CULL_*` in the runtime's scene.h. */
const CULL_CODES = { none: 0, back: 1, front: 2 } as const;

function numbers(values: readonly number[]): string {
  if (values.length === 0) return "0"; // C doesn't allow an empty array; the count says how many are real
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += PER_LINE) lines.push("  " + values.slice(i, i + PER_LINE).join(", "));
  return lines.join(",\n");
}

/**
 * Text that is safe inside a C comment on one line: printable ASCII only, and neither comment
 * delimiter can appear (a model's name comes from a file name, which can contain anything).
 */
import { cString } from "./label-text";

function commentSafe(text: string): string {
  return text
    .replace(/[^ -~]/g, "?")
    .replace(/\*\//g, "* /")
    .replace(/\/\*/g, "/ *")
    .slice(0, 60);
}

/** Texels are easier to read (and to compare with the picture) in hex. */
function hexNumbers(values: readonly number[]): string {
  if (values.length === 0) return "0";
  const lines: string[] = [];
  for (let i = 0; i < values.length; i += PER_LINE) {
    lines.push("  " + values.slice(i, i + PER_LINE).map((v) => "0x" + v.toString(16).padStart(4, "0")).join(", "));
  }
  return lines.join(",\n");
}

function matrix(m: readonly number[]): string {
  return `{ { ${m.join(", ")} } }`;
}

/** A float literal the C compiler reads back exactly. */
function float(value: number): string {
  const text = Number.isInteger(value) ? `${value}.0` : String(value);
  return `${text}f`;
}

/** The generated `script_code.c` (the scripts' functions and the table of script instances); it is built by `generateScriptCode` during translation. */
export function writeScriptCodeC(scene: DsScene3D): string {
  return scene.scriptCode;
}

/**
 * The C file for one scene of a project. `index` is the scene's place in the project's list (the starting scene is 0); the scene is `gs_scene_data_<index>`, and the runtime
 * picks the one it is showing through the table `writeSceneTableC` writes. The arrays are `static`, so scenes in separate files can't clash.
 */
export function writeSceneDataC(scene: DsScene3D, index = 0): string {
  const out: string[] = [];
  out.push("/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */");
  out.push('#include "scene.h"');
  out.push("");

  scene.primitives.forEach((p, i) => {
    out.push(`/* ${commentSafe(p.label)}: ${p.triangleCount} triangles */`);
    out.push(`static const int16_t primitive_${i}_positions[] = {\n${numbers(p.positions)}\n};`);
    out.push(`static const uint32_t primitive_${i}_normals[] = {\n${numbers(p.normals.map((n) => n))}\n};`);
    if (p.texcoords) out.push(`static const int16_t primitive_${i}_texcoords[] = {\n${numbers(p.texcoords)}\n};`);
    out.push("");
  });

  scene.textures.forEach((t, i) => {
    out.push(`/* texture ${commentSafe(t.label)}: ${t.width} x ${t.height}, ${t.width * t.height * 2} bytes */`);
    out.push(`static const uint16_t texture_${i}_texels[] = {\n${hexNumbers(t.texels)}\n};`);
    out.push("");
  });
  out.push("static const GsTexture textures[] = {");
  if (scene.textures.length === 0) out.push("  { 0, 0, 0, 0, 0 }");
  scene.textures.forEach((t, i) => {
    out.push(`  { ${t.width}, ${t.height}, ${t.sizeS}, ${t.sizeT}, texture_${i}_texels }${i < scene.textures.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  // Samples are 4-byte aligned: the sound hardware reads whole words from main RAM.
  scene.sounds.forEach((s, i) => {
    out.push(`/* sound ${commentSafe(s.label)}: ${s.samples.length} samples at ${s.sampleRate} Hz, ${s.samples.length * 2} bytes */`);
    out.push(`static const int16_t sound_${i}_samples[] __attribute__((aligned(4))) = {\n${numbers(s.samples)}\n};`);
    out.push("");
  });
  out.push("static const GsSound sounds[] = {");
  if (scene.sounds.length === 0) out.push("  { 0, 0, 0 }");
  scene.sounds.forEach((s, i) => {
    out.push(`  { ${s.samples.length}, ${s.sampleRate}, sound_${i}_samples }${i < scene.sounds.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAudioPlayer audioPlayers[] = {");
  if (scene.audioPlayers.length === 0) out.push("  { 0, 0, 0, 0, 0 }");
  scene.audioPlayers.forEach((p, i) => {
    out.push(`  { ${p.sound}, ${p.frequency}, ${p.volume}, ${p.loop ? 1 : 0}, ${p.autoplay ? 1 : 0} }${i < scene.audioPlayers.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  // A convex hull's points, one flat array shared by every hull collider: each one's hullStart/hullCount says which stretch of it is its own.
  const hullPoints: number[] = [];
  const hullRanges = scene.colliders.map((c) => {
    const start = hullPoints.length / 3;
    for (const [x, y, z] of c.hull ?? []) hullPoints.push(x, y, z);
    return { start, count: c.hull?.length ?? 0 };
  });
  out.push(`static const int32_t hull_points[] = {\n${numbers(hullPoints)}\n};`);
  out.push("");
  out.push("static const GsCollider colliders[] = {");
  if (scene.colliders.length === 0) out.push("  { 0, 0, { 0, 0, 0 }, 0, 0 }");
  scene.colliders.forEach((c, i) => {
    const { start, count } = hullRanges[i];
    out.push(`  { ${SHAPE_CODES[c.shape]}, ${c.solid ? 1 : 0}, { ${c.params.join(", ")} }, ${start}, ${count} }${i < scene.colliders.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsAnimKey animKeys[] = {");
  if (scene.animationKeys.length === 0) out.push("  { 0, { 0, 0, 0 } }");
  scene.animationKeys.forEach((k, i) => {
    out.push(`  { ${k.time}, { ${k.value.join(", ")} } }${i < scene.animationKeys.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimTrack animTracks[] = {");
  if (scene.animationTracks.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.animationTracks.forEach((t, i) => {
    out.push(`  { ${ANIM_PROPERTY_CODES[t.property]}, ${t.node}, ${t.keyStart}, ${t.keyCount} }${i < scene.animationTracks.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimation animations[] = {");
  if (scene.animations.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.animations.forEach((a, i) => {
    out.push(`  /* ${commentSafe(a.name)} */`);
    out.push(`  { ${a.length}, ${a.loop ? 1 : 0}, ${a.trackStart}, ${a.trackCount} }${i < scene.animations.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsAnimationPlayer animationPlayers[] = {");
  if (scene.animationPlayers.length === 0) out.push("  { 0, 0, -1, 0 }");
  scene.animationPlayers.forEach((p, i) => {
    out.push(`  { ${p.animationStart}, ${p.animationCount}, ${p.autoplay}, ${p.speed} }${i < scene.animationPlayers.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsTouchArea touchAreas[] = {");
  if (scene.touchAreas.length === 0) out.push("  { 0, 0, { 0, 0, 0, 0 }, { 0, 0, 0 } }");
  scene.touchAreas.forEach((t, i) => {
    out.push(`  { ${t.node}, ${TOUCH_SHAPE_CODES[t.shape]}, { ${t.rect.join(", ")} }, { ${t.params.join(", ")} } }${i < scene.touchAreas.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  out.push("static const GsPrimitive primitives[] = {");
  if (scene.primitives.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.primitives.forEach((p, i) => {
    const texcoords = p.texcoords ? `primitive_${i}_texcoords` : "0";
    out.push(`  { ${p.triangleCount}, primitive_${i}_positions, primitive_${i}_normals, ${texcoords} }${i < scene.primitives.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  // Every kept node, parents first. Meshes, the camera and lights say which one they are; scripts read and write the local values.
  out.push("static const GsNode nodes[] = {");
  scene.nodes.forEach((n, i) => {
    out.push(`  /* ${commentSafe(n.name)} */`);
    out.push(
      `  { ${n.parent}, ${n.dynamic ? 1 : 0}, ${n.visible ? 1 : 0}, ${n.audio}, ${n.collider}, ${n.animPlayer}, ${n.touch}, { ${n.position.join(", ")} }, { ${n.rotation.join(", ")} }, { ${n.scale.join(", ")} }, ` +
        `{ ${n.worldScale.join(", ")} }, ${matrix(n.world)} }${i < scene.nodes.length - 1 ? "," : ""}`
    );
  });
  out.push("};");
  out.push("");

  out.push(`static const uint16_t mesh_frames[] = { ${scene.meshFrames.length === 0 ? "0" : scene.meshFrames.join(", ")} };`);
  scene.meshAnimations.forEach((animation, i) => {
    out.push(`static const uint16_t mesh_animation_${i}_frames[] = { ${animation.frames.join(", ")} };`);
  });
  out.push("static const GsSpriteAnimation mesh_animations[] = {");
  if (scene.meshAnimations.length === 0) out.push("  { 0, 0, 0, 0 }");
  scene.meshAnimations.forEach((animation, i) => {
    out.push(`  { mesh_animation_${i}_frames, ${animation.frames.length}, ${animation.loop ? 1 : 0}, ${animation.step} }${i < scene.meshAnimations.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push("static const GsMesh meshes[] = {");
  if (scene.meshes.length === 0) out.push("  { 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 }");
  scene.meshes.forEach((m, i) => {
    out.push(
      `  { ${m.primitive}, ${m.diffuse}, ${m.texture}, ${m.node}, ${m.frameStart}, ${m.frameCount}, ${m.animation}, ${m.animationFirst}, ${m.animationCount}, ${m.unlit ? 1 : 0}, ${CULL_CODES[m.cull]} }${i < scene.meshes.length - 1 ? "," : ""}`
    );
  });
  out.push("};");
  out.push("");

  out.push("static const GsLight lights[] = {");
  if (scene.lights.length === 0) out.push("  { 0, { 0, 0, 0 }, 0 }");
  scene.lights.forEach((l, i) => {
    out.push(`  { ${l.color}, { ${l.direction.join(", ")} }, ${l.node} }${i < scene.lights.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");

  const twoD = writeScreen2DC(out, "two_d", scene.sprites2D, true);
  out.push(`const GsScene gs_scene_data_${index} = {`);
  out.push(`  ${scene.screen === "top" ? 0 : 1}, /* screen: 0 top, 1 bottom */`);
  out.push(`  ${scene.fps}, /* fps */`);
  out.push(`  ${float(scene.camera.fovDegrees)}, ${float(scene.camera.nearPlane)}, ${float(scene.camera.farPlane)}, ${float(scene.camera.tanHalfFov)}, /* fov, near, far, tan(fov / 2) */`);
  out.push(`  ${matrix(scene.camera.view)}, /* view */`);
  out.push(`  ${scene.camera.node}, ${scene.nodes.length}, /* camera node, node count */`);
  out.push(`  ${scene.primitives.length}, ${scene.meshes.length}, ${scene.lights.length}, ${scene.textures.length}, /* primitive, mesh, light, texture counts */`);
  out.push(`  ${scene.sounds.length}, ${scene.audioPlayers.length}, ${scene.colliders.length}, ${hullPoints.length / 3}, /* sound, audio player, collider, hull point counts */`);
  out.push(`  ${scene.animationPlayers.length}, ${scene.animations.length}, ${scene.animationTracks.length}, ${scene.animationKeys.length}, /* animation player, animation, track, key counts */`);
  out.push(`  ${scene.touchAreas.length}, /* touch area count */`);
  out.push(`  nodes, primitives, meshes, lights, textures, sounds, audioPlayers, colliders, hull_points, animationPlayers, animations, animTracks, animKeys, touchAreas, ${twoD}, ${scene.meshAnimations.length}, mesh_frames, mesh_animations`);
  out.push("};");
  out.push("");
  return out.join("\n");
}

/**
 * Serializes a translated 2D scene as the `scene2d_data.c` the 2D runtime is built against (packages/compiler/runtime2d). Like
 * `writeSceneDataC` it is constant data only and a pure function of the scene. The struct layouts are declared by the 2D
 * runtime's `scene2d.h`; keep the two in step.
 */
/** A number that says which global variables a game has (FNV-1a over their names and types, in order): the save file carries it, so a save from another version of the game isn't loaded. */
export function globalSignature(globals: ReadonlyArray<{ name: string; type: string }>): number {
  let hash = 2166136261;
  for (const byte of new TextEncoder().encode(globals.map((g) => `${g.name}:${g.type};`).join(""))) {
    hash ^= byte;
    hash = Math.imul(hash, 16777619) >>> 0;
  }
  return hash >>> 0;
}

/** Writes one screen's sprite images and sprites as constant arrays named after `name` and returns the `GsScreen2D` initializer that refers to them. */
function writeScreen2DC(out: string[], name: string, screen: DsScreen2D, live = false): string {
  screen.images.forEach((image, i) => {
    out.push(`/* ${name} screen image ${commentSafe(image.label)}: ${image.frames} frame${image.frames === 1 ? "" : "s"} of ${image.width} x ${image.height}, ${image.tiles.length} bytes */`);
    out.push(`static const uint16_t ${name}_image_${i}_palette[256] __attribute__((aligned(4))) = {\n${hexNumbers(image.palette)}\n};`);
    out.push(`static const uint8_t ${name}_image_${i}_tiles[] __attribute__((aligned(4))) = {\n${numbers(image.tiles)}\n};`);
    out.push("");
  });
  out.push(`static const GsSpriteImage ${name}_images[] = {`);
  if (screen.images.length === 0) out.push("  { 0, 0, 0, 0, 0 }");
  screen.images.forEach((image, i) => {
    out.push(`  { ${image.width}, ${image.height}, ${image.frames}, ${name}_image_${i}_palette, ${name}_image_${i}_tiles }${i < screen.images.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push(`static const GsSprite ${name}_sprites[] = {`);
  if (screen.sprites.length === 0) out.push(live ? "  { 0, 0, 0, -1, 0, -1, 0, 4096, 4096, -1, 0, 0 }" : "  { 0, 0, 0, -1, 0, 0 }");
  screen.sprites.forEach((sprite, i) => {
    out.push(`  /* ${commentSafe(sprite.name)} */`);
    const extra = live ? `, ${sprite.node ?? -1}, ${sprite.dynamic ? 1 : 0}, ${sprite.affine ?? -1}, ${sprite.rotation ?? 0}, ${sprite.scaleX ?? 4096}, ${sprite.scaleY ?? 4096}` : "";
    out.push(`  { ${sprite.x}, ${sprite.y}, ${sprite.image}${extra}, ${sprite.animation}, ${sprite.animationFirst}, ${sprite.animationCount} }${i < screen.sprites.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  screen.animations.forEach((animation, i) => {
    out.push(`static const uint16_t ${name}_animation_${i}_frames[] = { ${animation.frames.join(", ")} };`);
  });
  out.push(`static const GsSpriteAnimation ${name}_animations[] = {`);
  if (screen.animations.length === 0) out.push("  { 0, 0, 0, 0 }");
  screen.animations.forEach((animation, i) => {
    out.push(`  { ${name}_animation_${i}_frames, ${animation.frames.length}, ${animation.loop ? 1 : 0}, ${animation.step} }${i < screen.animations.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  out.push(`static const GsLabel ${name}_labels[] = {`);
  if (screen.labels.length === 0) out.push('  { 0, 0, 0, 0, -1, "" }');
  screen.labels.forEach((label, i) => {
    out.push(`  /* ${commentSafe(label.name)} */`);
    out.push(`  { ${label.column}, ${label.row}, ${label.color}, ${label.visible === false ? 0 : 1}, ${label.node ?? -1}, ${cString(label.text)} }${i < screen.labels.length - 1 ? "," : ""}`);
  });
  out.push("};");
  out.push("");
  return `{ ${screen.images.length}, ${screen.sprites.length}, ${name}_images, ${name}_sprites, ${screen.animations.length}, ${name}_animations, ${screen.labels.length}, ${name}_labels }`;
}

/** The table of a project's scenes: `gs_scene_table`, and `gs_scene_current`, which starts as the first (the starting scene). One file for all of them. */
export function writeSceneTableC(count: number): string {
  const out: string[] = [];
  out.push("/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */");
  out.push('#include "scene.h"');
  out.push("");
  for (let i = 0; i < count; i++) out.push(`extern const GsScene gs_scene_data_${i};`);
  out.push("");
  out.push("const GsScene *const gs_scene_table[] = {");
  for (let i = 0; i < count; i++) out.push(`  &gs_scene_data_${i}${i < count - 1 ? "," : ""}`);
  out.push("};");
  out.push(`const uint16_t gs_scene_table_count = ${count};`);
  out.push("const GsScene *gs_scene_current = &gs_scene_data_0;");
  out.push("");
  return out.join("\n");
}

/**
 * `script_code.c` for a project: every scene's script code (the first scene's names plain, the others' prefixed `sc1_`, `sc2_`, ...) and `gs_scene_scripts`, the table the runtime
 * reads to start a scene's scripts: each scene's instance table, how many there are, and the function that puts its script variables back to their starting values.
 */
export function writeScriptCodeFileC(scenes: readonly DsScene3D[]): string {
  const out: string[] = scenes.map((scene) => scene.scriptCode);
  // The global variables: one table for the whole game (every scene has the same), which the scenes' scripts and the save file use.
  const globals = scenes[0]?.globals ?? [];
  out.push("/* The project's global variables: kept when the scene changes, and what the save file holds. */");
  out.push('#include "gs_api.h"');
  out.push(`int32_t gs_global[${Math.max(1, globals.length)}] = { ${globals.length === 0 ? "0" : globals.map((g) => g.value).join(", ")} };`);
  out.push(`const int32_t gs_global_initial[${Math.max(1, globals.length)}] = { ${globals.length === 0 ? "0" : globals.map((g) => g.value).join(", ")} };`);
  out.push(`const uint16_t gs_global_count = ${globals.length};`);
  out.push(`const uint32_t gs_global_signature = ${globalSignature(globals)}u;`);
  out.push(...globals.map((g, i) => `/* gs_global[${i}] is ${commentSafe(g.name)} (${g.type}) */`));
  out.push("");
  out.push("/* The scripts of every scene. */");
  out.push('#include "gs_api.h"');
  for (let i = 0; i < scenes.length; i++) {
    const prefix = i === 0 ? "" : `sc${i}_`;
    out.push(`extern const GsScriptInstance ${prefix}gs_script_instances[];`);
    out.push(`extern const uint16_t ${prefix}gs_script_instance_count;`);
    out.push(`void ${prefix}gs_scripts_reset(void);`);
  }
  out.push("const GsSceneScripts gs_scene_scripts[] = {");
  for (let i = 0; i < scenes.length; i++) {
    const prefix = i === 0 ? "" : `sc${i}_`;
    out.push(`  { ${prefix}gs_script_instances, &${prefix}gs_script_instance_count, ${prefix}gs_scripts_reset }${i < scenes.length - 1 ? "," : ""}`);
  }
  out.push("};");
  out.push("");
  return out.join("\n");
}

export function writeScene2DDataC(scene: DsScene2D): string {
  const out: string[] = [];
  out.push("/* GENERATED by @goodstuff/compiler. Do not edit: the next build overwrites this file. */");
  out.push('#include "scene2d.h"');
  out.push("");

  const top = writeScreen2DC(out, "top", scene.top);
  const bottom = writeScreen2DC(out, "bottom", scene.bottom);
  out.push("const GsScene2D gs_scene2d = {");
  out.push(`  ${scene.fps}, /* fps */`);
  out.push(`  ${top}, /* top screen: image, sprite counts, images, sprites */`);
  out.push(`  ${bottom} /* bottom screen */`);
  out.push("};");
  out.push("");
  return out.join("\n");
}
