/*
 * The Good Stuff DS 2D runtime: draws whatever `gs_scene2d` (source/scene2d_data.c, generated by the compiler) describes with the DS's
 * two 2D engines: the main engine shows the top screen and the sub engine the bottom screen, each with its own sprite memory,
 * palettes and sprite table. A script (source/script_code2d.c, also generated) can run every frame and move, turn, scale, show,
 * hide or animate a sprite, or change a label's text or value -- gs_runtime2d.c keeps the node table it reads and writes and reads
 * buttons and touch; this file also plays the part of gs_sprites.c/gs_labels.c (the 3D runtime's own per-frame node-following),
 * since both screens' state already lives here.
 *
 * Requirements: requirements/compiler/STORY.compile-2d-scene-to-nds-rom.md, scene-designer/STORY.standalone-2d-scripting.md
 */
#include <nds.h>

#include <stdlib.h>

#include "gs_api.h"
#include "scene2d.h"
#include "gs_sprite_anim.h"
#include "gs_labels.h"
#include "gs_tilemap.h"

void gs_init_nodes2d(void);
void gs_read_input(void);
void gs_init_audio2d(void);
void gs_start_audio2d(void);

/* The backdrop behind the sprites. Not black, so screenshots can find each screen (the emulator tests read these values). */
#define TOP_BACKDROP RGB15(3, 5, 10)
#define BOTTOM_BACKDROP RGB15(10, 5, 3)

static SpriteSize size_of(int width, int height) {
	switch (width * 100 + height) {
	case 808: return SpriteSize_8x8;
	case 1616: return SpriteSize_16x16;
	case 3232: return SpriteSize_32x32;
	case 6464: return SpriteSize_64x64;
	case 1608: return SpriteSize_16x8;
	case 3208: return SpriteSize_32x8;
	case 3216: return SpriteSize_32x16;
	case 6432: return SpriteSize_64x32;
	case 816: return SpriteSize_8x16;
	case 832: return SpriteSize_8x32;
	case 1632: return SpriteSize_16x32;
	default: return SpriteSize_32x64;
	}
}

/* What one engine keeps besides the scene: where each frame of each image sits in sprite memory, how far each sprite's animation
   has got, and this screen's camera node (STORY.standalone-2d-camera.md), or -1 for none. */
typedef struct {
	OamState *oam;
	const GsScreen2D *screen;
	u16 **frames[16]; /* per image, the sprite memory of each of its frames */
	GsSpriteAnimState state[128];
	int cameraNode;
} ScreenState;
static ScreenState screens[2];

/* A pixel position from a position in f32 (20.12), rounded to the nearest whole pixel. */
static int round_px(int32_t f) { return (f + 2048) >> 12; }

/*
 * The rotation matrix of an affine sprite. The angle is in degrees (f32), clockwise on the screen; the hardware's angle is 0..32767 for a whole turn. The scale is
 * a factor on each axis (f32); the matrix wants its inverse in 8.8 fixed point. A scale of nothing (or a huge one, from a script) is held to what the editor
 * allows: 1/16 to 8 times, its sign (a flip) kept. Identical to the 3D runtime's own gs_sprites.c (oamSub there, parameterized here since either engine's
 * sprites can be affine).
 */
static void set_matrix(OamState *oam, int matrix, int32_t degrees, int32_t scale_x, int32_t scale_y) {
	const int angle = (int)(((int64_t)degrees * 32768) / (360 * 4096)) & 0x7FFF;
	int32_t sx = scale_x, sy = scale_y;
	if (sx > -256 && sx < 256) sx = sx < 0 ? -256 : 256;
	if (sy > -256 && sy < 256) sy = sy < 0 ? -256 : 256;
	if (sx > 32768) sx = 32768;
	if (sx < -32768) sx = -32768;
	if (sy > 32768) sy = 32768;
	if (sy < -32768) sy = -32768;
	oamRotateScale(oam, matrix, angle, (int)(1048576 / sx), (int)(1048576 / sy));
}

/* Brings a sprite up to date with its node: where it is (relative to the screen's camera, if it has one -- STORY.standalone-2d-camera.md),
   whether it is shown, and (with a rotation matrix) its angle and scale. See gs_sprites.c (the 3D runtime's own copy of this, for its
   one 2D screen) for the hidden/rotate-scale interaction this works around. */
static void follow_sprite(ScreenState *state, int index, const GsSprite *sprite, const GsSpriteImage *image) {
	const GsNodeState *ns = &gs_node_state[sprite->node];
	int32_t worldX = ns->position[0];
	int32_t worldY = ns->position[1];
	if (state->cameraNode >= 0) {
		worldX -= gs_node_state[state->cameraNode].position[0];
		worldY -= gs_node_state[state->cameraNode].position[1];
	}
	int x = round_px(worldX);
	int y = round_px(worldY);
	if (sprite->affine >= 0) {
		if (ns->visible) {
			oamSetAffineIndex(state->oam, index, sprite->affine, true);
			set_matrix(state->oam, sprite->affine, ns->rotation[2], ns->scale[0], ns->scale[1]);
		} else {
			oamSetAffineIndex(state->oam, index, -1, false);
			oamSetHidden(state->oam, index, true);
		}
		x -= image->width;
		y -= image->height;
	} else {
		x -= image->width / 2;
		y -= image->height / 2;
		oamSetHidden(state->oam, index, !ns->visible);
	}
	oamSetXY(state->oam, index, x, y);
}

/* Copies each image's frames into the engine's sprite memory (one block per frame) and its palette into the extended palette slot of the same number, then
   sets up one hardware sprite for each sprite of the screen, showing the first frame of the animation it starts with (or frame 0), at the rotation and scale
   it starts with if it has a rotation matrix. `palettes` is the engine's extended palette memory, mapped for writing. gs_init_nodes2d must already have run:
   a sprite a script can reach is brought up to date with its node once here too (and every frame after, in update_screen), the same as the 3D runtime does. */
static void load_screen(ScreenState *state, OamState *oam, const GsScreen2D *screen, u16 (*palettes)[256], int cameraNode) {
	state->oam = oam;
	state->screen = screen;
	state->cameraNode = cameraNode;
	for (int i = 0; i < 16; i++) state->frames[i] = 0;
	for (int i = 0; i < screen->imageCount && i < 16; i++) {
		const GsSpriteImage *image = &screen->images[i];
		const int bytes = image->width * image->height;
		state->frames[i] = malloc(sizeof(u16 *) * image->frameCount);
		for (int f = 0; f < image->frameCount; f++) {
			u16 *gfx = oamAllocateGfx(oam, size_of(image->width, image->height), SpriteColorFormat_256Color);
			state->frames[i][f] = gfx;
			if (gfx) dmaCopy(image->tiles + f * bytes, gfx, bytes);
		}
		for (int c = 0; c < 256; c++) palettes[i][c] = image->palette[c];
	}
	for (int i = 0; i < screen->spriteCount && i < 128; i++) {
		const GsSprite *sprite = &screen->sprites[i];
		const GsSpriteImage *image = &screen->images[sprite->image];
		GsSpriteAnimState *anim = &state->state[i];
		anim->animation = -1;
		anim->playing = 0;
		anim->frame = 0;
		if (sprite->animation >= 0) gs_anim_start(anim, screen->animations, sprite->animation);
		anim->shown = anim->frame;
		if (!state->frames[sprite->image] || !state->frames[sprite->image][anim->frame]) continue;
		const int rotating = sprite->affine >= 0;
		oamSet(oam, i, sprite->x, sprite->y, 0, sprite->image, size_of(image->width, image->height), SpriteColorFormat_256Color,
			state->frames[sprite->image][anim->frame], rotating ? sprite->affine : -1, rotating, false, false, false, false);
		if (rotating) set_matrix(oam, sprite->affine, sprite->rotation, sprite->scaleX, sprite->scaleY);
		if (sprite->dynamic && sprite->node >= 0) follow_sprite(state, i, sprite, image);
	}
}

/* One game frame of the screen: sprites a script can reach follow their nodes (scripts have run for this frame), and every animated sprite's
   animation moves on and shows the frame it is now on (a script may have started or stopped one that didn't begin playing). */
static void update_screen(ScreenState *state) {
	const GsScreen2D *screen = state->screen;
	for (int i = 0; i < screen->spriteCount && i < 128; i++) {
		const GsSprite *sprite = &screen->sprites[i];
		if (sprite->dynamic && sprite->node >= 0) follow_sprite(state, i, sprite, &screen->images[sprite->image]);
		if (sprite->animation < 0 && sprite->animationCount == 0) continue;
		GsSpriteAnimState *anim = &state->state[i];
		gs_anim_step(anim, screen->animations);
		if (anim->frame == anim->shown) continue;
		const GsSpriteImage *image = &screen->images[sprite->image];
		if (state->frames[sprite->image] && state->frames[sprite->image][anim->frame]) {
			oamSetGfx(state->oam, i, size_of(image->width, image->height), SpriteColorFormat_256Color, state->frames[sprite->image][anim->frame]);
		}
		anim->shown = anim->frame;
	}
}

/* The sprite that draws a node, and which screen it is on, or neither found (both -1). A node index is unique across the whole scene, so both screens'
   sprite lists are searched; `gs_sprite_play/stop/is_playing` (a script's play("name")/stop()/is_playing() on an AnimatedSprite2D) go through this. */
static void find_sprite(int node, int *screen, int *index) {
	for (int s = 0; s < 2; s++) {
		const GsScreen2D *sc = screens[s].screen;
		for (int i = 0; i < sc->spriteCount && i < 128; i++) {
			if (sc->sprites[i].node == node) {
				*screen = s;
				*index = i;
				return;
			}
		}
	}
	*screen = -1;
	*index = -1;
}

void gs_sprite_play(int node, int animation) {
	int s, i;
	find_sprite(node, &s, &i);
	if (s < 0) return;
	const GsSprite *sprite = &screens[s].screen->sprites[i];
	if (animation < 0 || animation >= sprite->animationCount) return;
	gs_anim_start(&screens[s].state[i], screens[s].screen->animations, sprite->animationFirst + animation);
}

void gs_sprite_stop(int node) {
	int s, i;
	find_sprite(node, &s, &i);
	if (s >= 0) screens[s].state[i].playing = 0;
}

int gs_sprite_is_playing(int node) {
	int s, i;
	find_sprite(node, &s, &i);
	return s >= 0 && screens[s].state[i].playing;
}

static GsLabelScreen labelScreens[2];
static GsTileMapState tileMapScreens[2];
static int haveTileMap[2]; /* whether screens[s]/tileMapScreens[s] above actually has one (STORY.standalone-2d-tilemaps.md) */

/* The one TileMap on a screen (translate-scene-2d.ts's collectTileMaps keeps at most one -- multiple-tilemaps warns about
   any more), or null. */
static const GsTileMap *tilemap_on_screen(int screen) {
	for (int i = 0; i < gs_scene2d.tileMapCount; i++) {
		if (gs_scene2d.tileMaps[i].screen == screen) return &gs_scene2d.tileMaps[i];
	}
	return 0;
}

/* The label a node is, and which screen it is on, or neither found (both -1). Searched across both screens the same way find_sprite is; a script's
   $Label.text/.value go through this. */
static void find_label(int node, int *screen, int *index) {
	for (int s = 0; s < 2; s++) {
		for (int i = 0; i < labelScreens[s].count; i++) {
			if (labelScreens[s].labels[i].node == node) {
				*screen = s;
				*index = i;
				return;
			}
		}
	}
	*screen = -1;
	*index = -1;
}

void gs_label_set_value(int node, int32_t value) {
	int s, i;
	find_label(node, &s, &i);
	if (s < 0 || labelScreens[s].value[i] == value) return;
	labelScreens[s].value[i] = value;
	labelScreens[s].dirty = 1;
}

int32_t gs_label_get_value(int node) {
	int s, i;
	find_label(node, &s, &i);
	return s < 0 ? 0 : labelScreens[s].value[i];
}

void gs_label_set_text(int node, const char *text) {
	int s, i;
	find_label(node, &s, &i);
	if (s < 0 || labelScreens[s].text[i] == text) return;
	labelScreens[s].text[i] = text;
	labelScreens[s].dirty = 1;
}

/* One game frame of a label screen: a label whose node a script hid or showed catches up, then the layer redraws if anything (that, a value or a text) changed. */
static void update_labels(GsLabelScreen *screen) {
	for (int i = 0; i < screen->count; i++) {
		const int node = screen->labels[i].node;
		if (node < 0) continue;
		const uint8_t visible = gs_node_state[node].visible != 0;
		if (visible != screen->shown[i]) {
			screen->shown[i] = visible;
			screen->dirty = 1;
		}
	}
	gs_labels_update(screen);
}

int main(void) {
	lcdMainOnTop();

	/* Sprite tile memory: 128 KB for each engine (bank B main, bank D sub). The extended palettes live in banks F (main) and I (sub);
	   they are mapped as plain memory while they are written, then as the engines' palettes. */
	vramSetBankB(VRAM_B_MAIN_SPRITE);
	vramSetBankD(VRAM_D_SUB_SPRITE);
	vramSetBankF(VRAM_F_LCD);
	vramSetBankI(VRAM_I_LCD);

	videoSetMode(MODE_0_2D | DISPLAY_SPR_ACTIVE | DISPLAY_SPR_1D_LAYOUT);
	videoSetModeSub(MODE_0_2D | DISPLAY_SPR_ACTIVE | DISPLAY_SPR_1D_LAYOUT);
	setBackdropColor(TOP_BACKDROP);
	setBackdropColorSub(BOTTOM_BACKDROP);

	oamInit(&oamMain, SpriteMapping_1D_32, true);
	oamInit(&oamSub, SpriteMapping_1D_32, true);

	/* The node table, before anything that follows one (a sprite that starts rotated or already moved by a script) is set up. */
	gs_init_nodes2d();

	load_screen(&screens[0], &oamMain, &gs_scene2d.top, VRAM_F_EXT_SPR_PALETTE, gs_scene2d.topCamera);
	load_screen(&screens[1], &oamSub, &gs_scene2d.bottom, VRAM_I_EXT_SPR_PALETTE, gs_scene2d.bottomCamera);

	vramSetBankF(VRAM_F_SPRITE_EXT_PALETTE);
	vramSetBankI(VRAM_I_SUB_SPRITE_EXT_PALETTE);

	/* Text and tile maps share background hardware: a label's console is BG0, a TileMap BG1 (gs_tilemap.h), never overlapping
	   VRAM. The main engine's bank A (128 KB) is roomy enough for both at once; the sub engine's label-sized bank H (32 KB)
	   isn't, so a TileMap on the bottom screen takes over the otherwise-unused bank C (128 KB) instead, and the bottom
	   label (if any) moves into it too, at its own usual offsets. */
	const GsTileMap *topTileMap = tilemap_on_screen(0);
	const GsTileMap *bottomTileMap = tilemap_on_screen(1);
	if (gs_scene2d.top.labelCount > 0 || topTileMap) vramSetBankA(VRAM_A_MAIN_BG);
	if (bottomTileMap) vramSetBankC(VRAM_C_SUB_BG);
	else if (gs_scene2d.bottom.labelCount > 0) vramSetBankH(VRAM_H_SUB_BG);
	gs_labels_start(&labelScreens[0], gs_scene2d.top.labels, gs_scene2d.top.labelCount, 1);
	gs_labels_start(&labelScreens[1], gs_scene2d.bottom.labels, gs_scene2d.bottom.labelCount, 0);
	if (topTileMap) {
		haveTileMap[0] = 1;
		gs_tilemap_start(&tileMapScreens[0], topTileMap, gs_scene2d.topCamera, 1);
	}
	if (bottomTileMap) {
		haveTileMap[1] = 1;
		gs_tilemap_start(&tileMapScreens[1], bottomTileMap, gs_scene2d.bottomCamera, 0);
	}
	/* The console loads its font palette over entry 0, which is the backdrop: put the backdrops back. */
	setBackdropColor(TOP_BACKDROP);
	setBackdropColorSub(BOTTOM_BACKDROP);

	gs_init_audio2d();
	gs_start_audio2d();

	/* Every script's _ready(), once, before the first frame draws -- whatever it changes already shows in that frame. */
	for (int i = 0; i < gs_script_instance_count; i++) {
		const GsScriptInstance *script = &gs_script_instances[i];
		if (script->ready) script->ready(script->inst);
	}

	/* 60 fps waits one vertical blank per frame, 30 fps waits two. Seconds per frame, as a 20.12 number. */
	const int framesPerPresent = gs_scene2d.fps == 30 ? 2 : 1;
	const int32_t delta = gs_scene2d.fps == 30 ? 137 : 68;
	while (pmMainLoop()) {
		for (int i = 0; i < framesPerPresent; i++) swiWaitForVBlank();
		gs_read_input();
		for (int i = 0; i < gs_script_instance_count; i++) {
			const GsScriptInstance *script = &gs_script_instances[i];
			if (script->process) script->process(script->inst, delta);
		}
		update_screen(&screens[0]);
		update_screen(&screens[1]);
		update_labels(&labelScreens[0]);
		update_labels(&labelScreens[1]);
		if (haveTileMap[0]) gs_tilemap_update(&tileMapScreens[0]);
		if (haveTileMap[1]) gs_tilemap_update(&tileMapScreens[1]);
		oamUpdate(&oamMain);
		oamUpdate(&oamSub);
		bgUpdate();
	}
	return 0;
}
