/*
 * The Good Stuff DS 2D runtime: draws whatever `gs_scene2d` (source/scene2d_data.c, generated by the compiler) describes with the DS's
 * two 2D engines: the main engine shows the top screen and the sub engine the bottom screen, each with its own sprite memory,
 * palettes and sprite table. There is deliberately no game logic here; if the runtime needs to know something, the data says it.
 *
 * Requirements: requirements/compiler/STORY.compile-2d-scene-to-nds-rom.md
 */
#include <nds.h>

#include <stdlib.h>

#include "scene2d.h"
#include "gs_sprite_anim.h"
#include "gs_labels.h"

/* The backdrop behind the sprites. Not black, so screenshots can find each screen (the emulator tests read these values). */
#define TOP_BACKDROP RGB15(3, 5, 10)
#define BOTTOM_BACKDROP RGB15(10, 5, 3)

static SpriteSize size_of(int width, int height) {
	switch (width * 100 + height) {
	case 808: return SpriteSize_8x8;
	case 1616: return SpriteSize_16x16;
	case 3232: return SpriteSize_32x32;
	case 6464: return SpriteSize_64x64;
	case 1608: return SpriteSize_16x8;
	case 3208: return SpriteSize_32x8;
	case 3216: return SpriteSize_32x16;
	case 6432: return SpriteSize_64x32;
	case 816: return SpriteSize_8x16;
	case 832: return SpriteSize_8x32;
	case 1632: return SpriteSize_16x32;
	default: return SpriteSize_32x64;
	}
}

/* What one engine keeps besides the scene: where each frame of each image sits in sprite memory, and how far each sprite's animation has got. */
typedef struct {
	OamState *oam;
	const GsScreen2D *screen;
	u16 **frames[16]; /* per image, the sprite memory of each of its frames */
	GsSpriteAnimState state[128];
} ScreenState;
static ScreenState screens[2];

/* Copies each image's frames into the engine's sprite memory (one block per frame) and its palette into the extended palette slot of the same number, then
   sets up one hardware sprite for each sprite of the screen, showing the first frame of the animation it starts with (or frame 0). `palettes` is the engine's
   extended palette memory, mapped for writing. */
static void load_screen(ScreenState *state, OamState *oam, const GsScreen2D *screen, u16 (*palettes)[256]) {
	state->oam = oam;
	state->screen = screen;
	for (int i = 0; i < 16; i++) state->frames[i] = 0;
	for (int i = 0; i < screen->imageCount && i < 16; i++) {
		const GsSpriteImage *image = &screen->images[i];
		const int bytes = image->width * image->height;
		state->frames[i] = malloc(sizeof(u16 *) * image->frameCount);
		for (int f = 0; f < image->frameCount; f++) {
			u16 *gfx = oamAllocateGfx(oam, size_of(image->width, image->height), SpriteColorFormat_256Color);
			state->frames[i][f] = gfx;
			if (gfx) dmaCopy(image->tiles + f * bytes, gfx, bytes);
		}
		for (int c = 0; c < 256; c++) palettes[i][c] = image->palette[c];
	}
	for (int i = 0; i < screen->spriteCount && i < 128; i++) {
		const GsSprite *sprite = &screen->sprites[i];
		const GsSpriteImage *image = &screen->images[sprite->image];
		GsSpriteAnimState *anim = &state->state[i];
		anim->animation = -1;
		anim->playing = 0;
		anim->frame = 0;
		if (sprite->animation >= 0) gs_anim_start(anim, screen->animations, sprite->animation);
		anim->shown = anim->frame;
		if (!state->frames[sprite->image] || !state->frames[sprite->image][anim->frame]) continue;
		oamSet(oam, i, sprite->x, sprite->y, 0, sprite->image, size_of(image->width, image->height), SpriteColorFormat_256Color,
			state->frames[sprite->image][anim->frame], -1, false, false, false, false, false);
	}
}

/* One game frame of every animated sprite of the screen: moves the animations on and shows the frame each one is now on. */
static void animate_screen(ScreenState *state) {
	const GsScreen2D *screen = state->screen;
	for (int i = 0; i < screen->spriteCount && i < 128; i++) {
		const GsSprite *sprite = &screen->sprites[i];
		if (sprite->animation < 0) continue;
		GsSpriteAnimState *anim = &state->state[i];
		gs_anim_step(anim, screen->animations);
		if (anim->frame == anim->shown) continue;
		const GsSpriteImage *image = &screen->images[sprite->image];
		if (state->frames[sprite->image] && state->frames[sprite->image][anim->frame]) {
			oamSetGfx(state->oam, i, size_of(image->width, image->height), SpriteColorFormat_256Color, state->frames[sprite->image][anim->frame]);
		}
		anim->shown = anim->frame;
	}
}

static GsLabelScreen labelScreens[2];

int main(void) {
	lcdMainOnTop();

	/* Sprite tile memory: 128 KB for each engine (bank B main, bank D sub). The extended palettes live in banks F (main) and I (sub);
	   they are mapped as plain memory while they are written, then as the engines' palettes. */
	vramSetBankB(VRAM_B_MAIN_SPRITE);
	vramSetBankD(VRAM_D_SUB_SPRITE);
	vramSetBankF(VRAM_F_LCD);
	vramSetBankI(VRAM_I_LCD);

	videoSetMode(MODE_0_2D | DISPLAY_SPR_ACTIVE | DISPLAY_SPR_1D_LAYOUT);
	videoSetModeSub(MODE_0_2D | DISPLAY_SPR_ACTIVE | DISPLAY_SPR_1D_LAYOUT);
	setBackdropColor(TOP_BACKDROP);
	setBackdropColorSub(BOTTOM_BACKDROP);

	oamInit(&oamMain, SpriteMapping_1D_32, true);
	oamInit(&oamSub, SpriteMapping_1D_32, true);

	load_screen(&screens[0], &oamMain, &gs_scene2d.top, VRAM_F_EXT_SPR_PALETTE);
	load_screen(&screens[1], &oamSub, &gs_scene2d.bottom, VRAM_I_EXT_SPR_PALETTE);

	vramSetBankF(VRAM_F_SPRITE_EXT_PALETTE);
	vramSetBankI(VRAM_I_SUB_SPRITE_EXT_PALETTE);

	/* Text: a background layer on each engine that has labels (main: bank A, sub: bank H). */
	if (gs_scene2d.top.labelCount > 0) vramSetBankA(VRAM_A_MAIN_BG);
	if (gs_scene2d.bottom.labelCount > 0) vramSetBankH(VRAM_H_SUB_BG);
	gs_labels_start(&labelScreens[0], gs_scene2d.top.labels, gs_scene2d.top.labelCount, 1);
	gs_labels_start(&labelScreens[1], gs_scene2d.bottom.labels, gs_scene2d.bottom.labelCount, 0);
	/* The console loads its font palette over entry 0, which is the backdrop: put the backdrops back. */
	setBackdropColor(TOP_BACKDROP);
	setBackdropColorSub(BOTTOM_BACKDROP);

	/* 60 fps waits one vertical blank per frame, 30 fps waits two. */
	const int framesPerPresent = gs_scene2d.fps == 30 ? 2 : 1;
	while (pmMainLoop()) {
		for (int i = 0; i < framesPerPresent; i++) swiWaitForVBlank();
		animate_screen(&screens[0]);
		animate_screen(&screens[1]);
		gs_labels_update(&labelScreens[0]);
		gs_labels_update(&labelScreens[1]);
		oamUpdate(&oamMain);
		oamUpdate(&oamSub);
	}
	return 0;
}
