import { spawnSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { PNG } from "pngjs";

import { NodeBuildFileSystem, NodeBuildRunner, NodeToolchainLocator } from "../build/node-adapters";
import { RomBuilder } from "../build/rom-builder";
import type { DsScene3D } from "../ds-scene";

/**
 * Test support: run generated code on the real ARM and read the answers back, when the development machine has no C compiler of its own to
 * run it on. A test ROM (the real runtime without its renderer, plus a `main` the test writes) evaluates C expressions and draws each 32-bit
 * result on the top screen as three colored 8 x 8 blocks (15 + 15 + 2 bits), inside a solid magenta frame that shows where the screen is.
 * An emulator capture is decoded back into the numbers. The first results are fixed values, so a decoding that isn't exact fails loudly.
 *
 * Used by script-semantics.rom.test.ts (requirements/compiler/TASK.compile-scripts-to-c.md).
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const RUNTIME_DIR = resolve(HERE, "..", "..", "runtime");
const CAPTURE_SCRIPT = resolve(HERE, "..", "..", "..", "..", "tools", "ds-toolchain", "capture-melonds.ps1");

/** Screen size in 8 x 8 blocks, and the frame (outer ring) that leaves. */
const GRID_W = 32;
const GRID_H = 24;
const INTERIOR_W = GRID_W - 2;
const INTERIOR_H = GRID_H - 2;
/** Three blocks per result. */
export const MAX_DUMP_RESULTS = Math.floor((INTERIOR_W * INTERIOR_H) / 3);

/** The first results, known in advance: they prove that every bit of a 32-bit value survives the picture. */
export const CALIBRATION = [0x5a5aa5a5, 0x00000000, -1, -2147483648, 0x12345678, 0x0fedcba9 | 0];

export interface DumpItem {
  /** C statements run before the expression (set up input, node states, call a function for its side effects). */
  setup?: string;
  /** A C expression of an integer type: its value (as int32) is what is drawn. */
  expr: string;
}

function dumpMainC(items: readonly DumpItem[]): string {
  const all: DumpItem[] = [...CALIBRATION.map((v) => ({ expr: v === -2147483648 ? "(int32_t)0x80000000" : String(v) })), ...items];
  if (all.length > MAX_DUMP_RESULTS) throw new Error(`Too many results for one picture (${all.length}; the most is ${MAX_DUMP_RESULTS}).`);
  const body = all.map((item, i) => `\t{ ${item.setup ?? ""} results[${i}] = (int32_t)(${item.expr}); }`).join("\n");
  return `/* GENERATED by the script test harness. */
#include <nds.h>
#include <stdlib.h>

#include "gs_api.h"
#include "gs_runtime.h"
#include "scene.h"
#include "script_generated.h"

#define RESULT_COUNT ${all.length}
static int32_t results[RESULT_COUNT];

static void draw_results(void) {
	videoSetMode(MODE_FB0);
	vramSetBankA(VRAM_A_LCD);
	lcdMainOnTop();
	videoSetModeSub(MODE_0_2D);
	setBackdropColorSub(RGB15(0, 0, 0));
	uint16_t *fb = VRAM_A;
	for (int y = 0; y < 192; y++) {
		for (int x = 0; x < 256; x++) {
			int bx = x / 8, by = y / 8;
			uint16_t color;
			if (bx == 0 || by == 0 || bx == ${GRID_W - 1} || by == ${GRID_H - 1}) {
				color = RGB15(31, 0, 31);
			} else {
				int block = (by - 1) * ${INTERIOR_W} + (bx - 1);
				int result = block / 3, part = block % 3;
				color = 0;
				if (result < RESULT_COUNT) {
					uint32_t v = (uint32_t)results[result];
					color = (uint16_t)(part == 0 ? (v & 0x7fff) : part == 1 ? ((v >> 15) & 0x7fff) : ((v >> 30) & 3));
				}
			}
			fb[y * 256 + x] = color | 0x8000;
		}
	}
}

int main(void) {
	gs_init_nodes();
${body}
	draw_results();
	for (;;) swiWaitForVBlank();
	return 0;
}
`;
}

export interface DumpResult {
  values: number[];
  pngPath: string;
}

/**
 * Builds a ROM from `scene` (whose generated script code becomes `script_generated.h`, included by the test's `main`, so the script's static
 * functions and state can be called directly) and runs `items` on it.
 */
export async function runDump(scene: DsScene3D, items: readonly DumpItem[], workDir: string, name: string, waitSeconds = 5): Promise<DumpResult> {
  const runtime = join(workDir, `${name}-runtime`);
  rmSync(runtime, { recursive: true, force: true });
  cpSync(RUNTIME_DIR, runtime, { recursive: true });
  rmSync(join(runtime, "source", "main.c"));
  rmSync(join(runtime, "source", "script_code.c"));
  writeFileSync(join(runtime, "include", "script_generated.h"), scene.scriptCode);
  writeFileSync(join(runtime, "source", "test_main.c"), dumpMainC(items));

  const builder = new RomBuilder({ locator: new NodeToolchainLocator(), runner: new NodeBuildRunner(), fs: new NodeBuildFileSystem(), runtimeDir: runtime });
  const rom = join(workDir, `${name}.nds`);
  // The build driver writes script_code.c from the scene; the generated code is included by test_main.c instead, so that file is left empty.
  const built = await builder.build({ ...scene, scriptCode: "/* the scripts are in script_generated.h for this test */\n" }, rom);
  if (!built.ok) throw new Error(`Building the test ROM failed: ${built.message}\n${"output" in built ? built.output : ""}`);

  const pngPath = join(workDir, `${name}.png`);
  const run = spawnSync("powershell", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", CAPTURE_SCRIPT, "-Rom", rom, "-Out", pngPath, "-WaitSeconds", String(waitSeconds)], {
    encoding: "utf-8",
    timeout: 60_000 + waitSeconds * 1000
  });
  if (run.status !== 0) throw new Error(`Capturing the emulator failed:\n${run.stdout}\n${run.stderr}`);
  const values = decodeDump(pngPath, CALIBRATION.length + items.length).slice(CALIBRATION.length);
  return { values, pngPath };
}

/** Reads `count` results out of a capture of the dump ROM, checking the calibration values first. */
export function decodeDump(pngPath: string, count: number): number[] {
  const png = PNG.sync.read(readFileSync(pngPath));
  const at = (x: number, y: number): [number, number, number] => {
    const i = (y * png.width + x) * 4;
    return [png.data[i], png.data[i + 1], png.data[i + 2]];
  };
  // The screen is the bounding box of the magenta frame.
  let left = png.width;
  let top = png.height;
  let right = -1;
  let bottom = -1;
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      const [r, g, b] = at(x, y);
      if (r > 200 && g < 60 && b > 200) {
        if (x < left) left = x;
        if (x > right) right = x;
        if (y < top) top = y;
        if (y > bottom) bottom = y;
      }
    }
  }
  if (right < 0) throw new Error(`No magenta frame in ${pngPath}: the test ROM didn't draw its results, or the window was covered.`);
  const width = right - left + 1;
  const height = bottom - top + 1;
  if (Math.abs(width / height - 4 / 3) > 0.03) throw new Error(`The frame in ${pngPath} is ${width}x${height}, which isn't the DS screen's shape. Was another window in front of the emulator?`);

  const blockWidth = width / GRID_W;
  const blockHeight = height / GRID_H;
  const blockValue = (block: number): number => {
    const bx = 1 + (block % INTERIOR_W);
    const by = 1 + Math.floor(block / INTERIOR_W);
    const [r, g, b] = at(Math.min(png.width - 1, Math.floor(left + (bx + 0.5) * blockWidth)), Math.min(png.height - 1, Math.floor(top + (by + 0.5) * blockHeight)));
    const five = (channel: number): number => Math.round((channel * 31) / 255);
    return five(r) | (five(g) << 5) | (five(b) << 10);
  };

  const values: number[] = [];
  for (let i = 0; i < count; i++) {
    const low = blockValue(i * 3);
    const middle = blockValue(i * 3 + 1);
    const high = blockValue(i * 3 + 2) & 3;
    values.push(((low | (middle << 15)) >>> 0 | (high << 30)) | 0);
  }
  CALIBRATION.forEach((expected, i) => {
    if (values[i] !== expected) {
      throw new Error(`The picture didn't decode exactly: result ${i} should be ${expected} but was ${values[i]}. See ${pngPath}. (${values.slice(0, CALIBRATION.length).join(", ")})`);
    }
  });
  return values;
}

/** Makes a temp directory's parents exist. */
export function ensureDir(dir: string): void {
  mkdirSync(dir, { recursive: true });
}
